/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    CaCertManager: typeof import('./src/components/panel/CaCertManager.vue')['default']
    Card: typeof import('primevue/card')['default']
    CertInfoDlg: typeof import('./src/components/panel/SslCertMgr/dialog/SslCertInfoDlg.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    copy: typeof import('./src/components/dialog/EditDisplayName copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DelSslCertDia: typeof import('./src/components/panel/SslCertMgr/dialog/DelSslCertDlg.vue')['default']
    DelSslCertDlg: typeof import('./src/components/panel/SslCertMgr/dialog/DelSslCertDlg.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditDisplayName: typeof import('./src/components/dialog/EditDisplayName.vue')['default']
    EditEmail: typeof import('./src/components/dialog/EditEmail.vue')['default']
    EditPassword: typeof import('./src/components/dialog/EditPassword.vue')['default']
    EditSslCertDlg: typeof import('./src/components/panel/SslCertMgr/dialog/EditSslCertDlg.vue')['default']
    ExportCertDlg: typeof import('./src/components/panel/SslCertMgr/dialog/ExportCertDlg.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Paginator: typeof import('primevue/paginator')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RenewSslCertClg: typeof import('./src/components/panel/SslCertMgr/dialog/RenewSslCertDlg.vue')['default']
    RenewSslCertDlg: typeof import('./src/components/panel/SslCertMgr/dialog/RenewSslCertDlg.vue')['default']
    ReqNewSslCertDlg: typeof import('./src/components/panel/SslCertMgr/dialog/ReqNewSslCertDlg.vue')['default']
    RequestNewCa: typeof import('./src/components/dialog/RequestNewCa.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SslCertInfoDlg: typeof import('./src/components/panel/SslCertMgr/dialog/SslCertInfoDlg.vue')['default']
    SslCertMgr: typeof import('./src/components/panel/SslCertMgr/index.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
