/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    copy: typeof import('./src/components/dialog/EditDisplayName copy.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditDisplayName: typeof import('./src/components/dialog/EditDisplayName.vue')['default']
    EditEmail: typeof import('./src/components/dialog/EditEmail.vue')['default']
    EditPassword: typeof import('./src/components/dialog/EditPassword.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
