/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CertMgr: typeof import('./src/components/panel/CertMgr.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DispCertInfoDlg: typeof import('./src/components/dialog/cert/DispCertInfoDlg.vue')['default']
    EditCertCmtDlg: typeof import('./src/components/dialog/cert/EditCertCmtDlg.vue')['default']
    EditDispName: typeof import('./src/components/dialog/profile/EditDispName.vue')['default']
    EditEmail: typeof import('./src/components/dialog/profile/EditEmail.vue')['default']
    EditPasswd: typeof import('./src/components/dialog/profile/EditPasswd.vue')['default']
    ExCertDlg: typeof import('./src/components/dialog/cert/ExCertDlg.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    IconField: typeof import('primevue/iconfield')['default']
    ImCaDlg: typeof import('./src/components/dialog/cert/ImCaDlg.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RenewCertDlg: typeof import('./src/components/dialog/cert/RenewCertDlg.vue')['default']
    ReqNewCertDlg: typeof import('./src/components/dialog/cert/ReqNewCertDlg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UsrMgr: typeof import('./src/components/panel/UsrMgr.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
