package com.gregperlinli.certvault.certificate;

import com.gregperlinli.certvault.domain.entities.CertGenRequest;
import com.gregperlinli.certvault.domain.entities.CertRenewRequest;
import com.gregperlinli.certvault.domain.entities.GenResponse;
import com.gregperlinli.certvault.domain.entities.SubjectAltName;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.List;

/**
 * SSL Certificate Generator Test
 *
 * @author gregPerlinLi
 * @version 1.0.0
 * @className {@code SslCertGeneratorTest}
 * @date 2025/3/15 14:58
 */
@SpringBootTest
@Slf4j
public class SslCertGeneratorTest {

    @Test
    public void testGenerateSslCertificate() {
        CertGenRequest request = new CertGenRequest()
                //.setCaKey("LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSDNBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIZk1JSGNBZ0VCQkVJQUUycUZXQmxsbkJnbFUrK3oKbEE4TXcvbmVLeWtJNlhWcTNyK2Z3aEtHakZsT0xhemU4MGVpRUpKTFdIcG02a1JFMUFHcEdIUDg1NmVHeHhPTApRZjBUbmN1Z0J3WUZLNEVFQUNPaGdZa0RnWVlBQkFBMmVKOFVqcVhyeTE4QjJSTmJHVXJsNFQ0Z3ZMNXhqblBpCkR6K1ZkS3NrN2VEREdmS2FlQUhpRVFTOGpOZEVGSmhGU3RrTGhhbFpleXdSZ2tsd1c4QjZYZ0RWc01sNXRQZzgKcExoVGtTVDkrRUtmTERlT0Z6bUNCaUF0TGNwR1VGWkNCQzFwZnZRTmtCYU9RdTRDc1RrU3Fkcml2NklhZk5EbQphUHVpTG1iUWY4dFo4Zz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K")
                //.setCa("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNwVENDQWt1Z0F3SUJBZ0lSQVB2dllVRWRRQm01MlZlNC9mMFlOa3N3Q2dZSUtvWkl6ajBFQXdJd2daMHgKQ3pBSkJnTlZCQVlUQWtOT01SSXdFQVlEVlFRSURBbEhkV0Z1WjJSdmJtY3hEekFOQmdOVkJBY01Ca05oYm5SdgpiakVWTUJNR0ExVUVDZ3dNUjNKbFoxQmxjbXhwYmt4cE1SSXdFQVlEVlFRTERBbERaWEowVm1GMWJIUXhGVEFUCkJnTlZCQU1NREVObGNuUldZWFZzZENCRFFURW5NQ1VHQ1NxR1NJYjNEUUVKQVJZWVozSmxaMUJsY214cGJreHAKUUc5MWRHeHZiMnN1WTI5dE1CNFhEVEkxTURReU1ERXlORGd4TjFvWERUTXdNRE15TlRFeU5EZ3hOMW93Z1o0eApDekFKQmdOVkJBWVRBa05PTVJJd0VBWURWUVFJREFsSGRXRnVaMlJ2Ym1jeER6QU5CZ05WQkFjTUJrTmhiblJ2CmJqRU5NQXNHQTFVRUNnd0VWR1Z6ZERFWE1CVUdBMVVFQ3d3T1EyVnlkRlpoZFd4MElGUmxjM1F4R1RBWEJnTlYKQkFNTUVFTmxjblJXWVhWc2RDQkpiblFnUTBFeEp6QWxCZ2txaGtpRzl3MEJDUUVXR0dkeVpXZFFaWEpzYVc1TQphVUJ2ZFhSc2IyOXJMbU52YlRDQm16QVFCZ2NxaGtqT1BRSUJCZ1VyZ1FRQUl3T0JoZ0FFQURaNG54U09wZXZMClh3SFpFMXNaU3VYaFBpQzh2bkdPYytJUFA1VjBxeVR0NE1NWjhwcDRBZUlSQkx5TTEwUVVtRVZLMlF1RnFWbDcKTEJHQ1NYQmJ3SHBlQU5Xd3lYbTArRHlrdUZPUkpQMzRRcDhzTjQ0WE9ZSUdJQzB0eWtaUVZrSUVMV2wrOUEyUQpGbzVDN2dLeE9SS3AydUsvb2hwODBPWm8rNkl1WnRCL3kxbnlveVl3SkRBT0JnTlZIUThCQWY4RUJBTUNBWVl3CkVnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFoUVZGNlR6WUVPZjAKbG9WSXY4SHVDYUJDU2YvVkQ4MjFqUlhZTk9wZUJEc0NJRy8yOWRDbHhvb3NtRDVNN3R1eVZqWUtUWEp2RGdKTgozdGxIaUd5YUFJSi8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=")
                .setCaKey("LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1GRUNBUUV3QlFZREsyVndCQ0lFSU0xRW9XVkk4YjVHR0tnWnVEV0xmVnpwTTdUQk9COCtNbGRiN0wxRW5za2QKZ1NFQWxKZ2RPVjR2N1VrZndrakxYdDA2VmhmMGpLbVkyOTBjZ2MxdUl3ZXVYSm89Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K")
                .setCa("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNJakNDQWRTZ0F3SUJBZ0lSQVByNk5CN3J6di96VndaMUR3dkZQTUV3QlFZREsyVndNSUdkTVFzd0NRWUQKVlFRR0V3SkRUakVTTUJBR0ExVUVDQXdKUjNWaGJtZGtiMjVuTVE4d0RRWURWUVFIREFaRFlXNTBiMjR4RlRBVApCZ05WQkFvTURFZHlaV2RRWlhKc2FXNU1hVEVTTUJBR0ExVUVDd3dKUTJWeWRGWmhkV3gwTVJVd0V3WURWUVFECkRBeERaWEowVm1GMWJIUWdRMEV4SnpBbEJna3Foa2lHOXcwQkNRRVdHR2R5WldkUVpYSnNhVzVNYVVCdmRYUnMKYjI5ckxtTnZiVEFlRncweU5UQTBNakF4TXpBNE5ESmFGdzB6TURBek1qVXhNekE0TkRKYU1JR2VNUXN3Q1FZRApWUVFHRXdKRFRqRVNNQkFHQTFVRUNBd0pSM1ZoYm1ka2IyNW5NUTh3RFFZRFZRUUhEQVpEWVc1MGIyNHhEVEFMCkJnTlZCQW9NQkZSbGMzUXhGekFWQmdOVkJBc01Ea05sY25SV1lYVnNkQ0JVWlhOME1Sa3dGd1lEVlFRRERCQkQKWlhKMFZtRjFiSFFnU1c1MElFTkJNU2N3SlFZSktvWklodmNOQVFrQkZoaG5jbVZuVUdWeWJHbHVUR2xBYjNWMApiRzl2YXk1amIyMHdLakFGQmdNclpYQURJUUNVbUIwNVhpL3RTUi9DU010ZTNUcFdGL1NNcVpqYjNSeUJ6VzRqCkI2NWNtcU1tTUNRd0RnWURWUjBQQVFIL0JBUURBZ0dHTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0JRWUQKSzJWd0EwRUE0Sk5WQ3hTRGEvRDZhWEtidUJPNFVmVnhMcXFVaTNDR0ZpeFZPTTkrbnJWV1FuSzl3TE9NQStjUQo1M1M5Q2pWZDB4cE93bWpjaXhnQ245amlFb2d2Q3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==")
                .setKeySize(384)
                .setCountry("CN")
                .setProvince("Guangdong")
                .setCity("Canton")
                .setOrganization("GregPerlinLi")
                .setOrganizationalUnit("CertVault")
                .setCommonName("cv.gpl.ac.cn")
                .setEmailAddress("gregPerlinLi@outlook.com")
                .setSubjectAltNames(List.of(
                        new SubjectAltName(SubjectAltName.Type.DNS_NAME, "cv.gpl.ac.cn"),
                        new SubjectAltName(SubjectAltName.Type.IP_ADDRESS, "10.18.0.1"),
                        new SubjectAltName(SubjectAltName.Type.EMAIL, "gregPerlinLi@outlook.com"),
                        new SubjectAltName(SubjectAltName.Type.URI, "https://cv.gpl.ac.cn")
                ))
                .setExpiry(30)
                .setComment("This is a Test SSL Certificate.");

        GenResponse response = SslCertGenerator.generateSslCertificate(request);

        log.debug(response.toString());
        log.info("SSL Private Key: \n {}", new String(java.util.Base64.getDecoder().decode(response.getPrivkey())));
        log.info("SSL Certificate: \n {}", new String(java.util.Base64.getDecoder().decode(response.getCert())));
        log.info("SSL Certificate Start Date: {}", response.getNotBefore());
        log.info("SSL Certificate End Date: {}", response.getNotAfter());
    }

    @Test
    public void testRenewSslCertificate() {
        CertRenewRequest request = new CertRenewRequest()
                //.setCaKey("LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSDNBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIZk1JSGNBZ0VCQkVJQUUycUZXQmxsbkJnbFUrK3oKbEE4TXcvbmVLeWtJNlhWcTNyK2Z3aEtHakZsT0xhemU4MGVpRUpKTFdIcG02a1JFMUFHcEdIUDg1NmVHeHhPTApRZjBUbmN1Z0J3WUZLNEVFQUNPaGdZa0RnWVlBQkFBMmVKOFVqcVhyeTE4QjJSTmJHVXJsNFQ0Z3ZMNXhqblBpCkR6K1ZkS3NrN2VEREdmS2FlQUhpRVFTOGpOZEVGSmhGU3RrTGhhbFpleXdSZ2tsd1c4QjZYZ0RWc01sNXRQZzgKcExoVGtTVDkrRUtmTERlT0Z6bUNCaUF0TGNwR1VGWkNCQzFwZnZRTmtCYU9RdTRDc1RrU3Fkcml2NklhZk5EbQphUHVpTG1iUWY4dFo4Zz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K")
                //.setCa("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNwVENDQWt1Z0F3SUJBZ0lSQVB2dllVRWRRQm01MlZlNC9mMFlOa3N3Q2dZSUtvWkl6ajBFQXdJd2daMHgKQ3pBSkJnTlZCQVlUQWtOT01SSXdFQVlEVlFRSURBbEhkV0Z1WjJSdmJtY3hEekFOQmdOVkJBY01Ca05oYm5SdgpiakVWTUJNR0ExVUVDZ3dNUjNKbFoxQmxjbXhwYmt4cE1SSXdFQVlEVlFRTERBbERaWEowVm1GMWJIUXhGVEFUCkJnTlZCQU1NREVObGNuUldZWFZzZENCRFFURW5NQ1VHQ1NxR1NJYjNEUUVKQVJZWVozSmxaMUJsY214cGJreHAKUUc5MWRHeHZiMnN1WTI5dE1CNFhEVEkxTURReU1ERXlORGd4TjFvWERUTXdNRE15TlRFeU5EZ3hOMW93Z1o0eApDekFKQmdOVkJBWVRBa05PTVJJd0VBWURWUVFJREFsSGRXRnVaMlJ2Ym1jeER6QU5CZ05WQkFjTUJrTmhiblJ2CmJqRU5NQXNHQTFVRUNnd0VWR1Z6ZERFWE1CVUdBMVVFQ3d3T1EyVnlkRlpoZFd4MElGUmxjM1F4R1RBWEJnTlYKQkFNTUVFTmxjblJXWVhWc2RDQkpiblFnUTBFeEp6QWxCZ2txaGtpRzl3MEJDUUVXR0dkeVpXZFFaWEpzYVc1TQphVUJ2ZFhSc2IyOXJMbU52YlRDQm16QVFCZ2NxaGtqT1BRSUJCZ1VyZ1FRQUl3T0JoZ0FFQURaNG54U09wZXZMClh3SFpFMXNaU3VYaFBpQzh2bkdPYytJUFA1VjBxeVR0NE1NWjhwcDRBZUlSQkx5TTEwUVVtRVZLMlF1RnFWbDcKTEJHQ1NYQmJ3SHBlQU5Xd3lYbTArRHlrdUZPUkpQMzRRcDhzTjQ0WE9ZSUdJQzB0eWtaUVZrSUVMV2wrOUEyUQpGbzVDN2dLeE9SS3AydUsvb2hwODBPWm8rNkl1WnRCL3kxbnlveVl3SkRBT0JnTlZIUThCQWY4RUJBTUNBWVl3CkVnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFoUVZGNlR6WUVPZjAKbG9WSXY4SHVDYUJDU2YvVkQ4MjFqUlhZTk9wZUJEc0NJRy8yOWRDbHhvb3NtRDVNN3R1eVZqWUtUWEp2RGdKTgozdGxIaUd5YUFJSi8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=")
                .setCaKey("LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1GRUNBUUV3QlFZREsyVndCQ0lFSU0xRW9XVkk4YjVHR0tnWnVEV0xmVnpwTTdUQk9COCtNbGRiN0wxRW5za2QKZ1NFQWxKZ2RPVjR2N1VrZndrakxYdDA2VmhmMGpLbVkyOTBjZ2MxdUl3ZXVYSm89Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K")
                .setCa("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNJakNDQWRTZ0F3SUJBZ0lSQVByNk5CN3J6di96VndaMUR3dkZQTUV3QlFZREsyVndNSUdkTVFzd0NRWUQKVlFRR0V3SkRUakVTTUJBR0ExVUVDQXdKUjNWaGJtZGtiMjVuTVE4d0RRWURWUVFIREFaRFlXNTBiMjR4RlRBVApCZ05WQkFvTURFZHlaV2RRWlhKc2FXNU1hVEVTTUJBR0ExVUVDd3dKUTJWeWRGWmhkV3gwTVJVd0V3WURWUVFECkRBeERaWEowVm1GMWJIUWdRMEV4SnpBbEJna3Foa2lHOXcwQkNRRVdHR2R5WldkUVpYSnNhVzVNYVVCdmRYUnMKYjI5ckxtTnZiVEFlRncweU5UQTBNakF4TXpBNE5ESmFGdzB6TURBek1qVXhNekE0TkRKYU1JR2VNUXN3Q1FZRApWUVFHRXdKRFRqRVNNQkFHQTFVRUNBd0pSM1ZoYm1ka2IyNW5NUTh3RFFZRFZRUUhEQVpEWVc1MGIyNHhEVEFMCkJnTlZCQW9NQkZSbGMzUXhGekFWQmdOVkJBc01Ea05sY25SV1lYVnNkQ0JVWlhOME1Sa3dGd1lEVlFRRERCQkQKWlhKMFZtRjFiSFFnU1c1MElFTkJNU2N3SlFZSktvWklodmNOQVFrQkZoaG5jbVZuVUdWeWJHbHVUR2xBYjNWMApiRzl2YXk1amIyMHdLakFGQmdNclpYQURJUUNVbUIwNVhpL3RTUi9DU010ZTNUcFdGL1NNcVpqYjNSeUJ6VzRqCkI2NWNtcU1tTUNRd0RnWURWUjBQQVFIL0JBUURBZ0dHTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0JRWUQKSzJWd0EwRUE0Sk5WQ3hTRGEvRDZhWEtidUJPNFVmVnhMcXFVaTNDR0ZpeFZPTTkrbnJWV1FuSzl3TE9NQStjUQo1M1M5Q2pWZDB4cE93bWpjaXhnQ245amlFb2d2Q3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==")
                .setUuid("e8e62fe9-b781-48df-832c-27f708fc6442")
                //.setOldPrivkey("LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JRy9BZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQklHbk1JR2tBZ0VCQkRBOEROWVplQ3ZQanQzWklEVTMKRXpmamRkVDZJdzFqeFpTKy9rMCtpMmJzazhEK1BpWkNORUlzTXU2bmNEeWVZQ2FnQndZRks0RUVBQ0toWkFOaQpBQVRUdk80cnlLRmg3SjBiYkxDVGpweS9JV2RYMnVISit3aXluZzRBT2tyY3AyZlMrMTdPSEhYdlozdnYxV3JhCi9jaHYzUElETFJYTU9nQnFJclZiMFhzYS9HR1lEMEJCdFVGeWVXazVRV3FvOGtIUW5NQ1luV0tTWlRCOG5oN0EKNXpzPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==")
                //.setOldCert("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIakNDQW9DZ0F3SUJBZ0lSQUpCWWlrTG15WlU3WVJpUWhqZzhkaGt3Q2dZSUtvWkl6ajBFQXdJd2daNHgKQ3pBSkJnTlZCQVlUQWtOT01SSXdFQVlEVlFRSURBbEhkV0Z1WjJSdmJtY3hEekFOQmdOVkJBY01Ca05oYm5SdgpiakVOTUFzR0ExVUVDZ3dFVkdWemRERVhNQlVHQTFVRUN3d09RMlZ5ZEZaaGRXeDBJRlJsYzNReEdUQVhCZ05WCkJBTU1FRU5sY25SV1lYVnNkQ0JKYm5RZ1EwRXhKekFsQmdrcWhraUc5dzBCQ1FFV0dHZHlaV2RRWlhKc2FXNU0KYVVCdmRYUnNiMjlyTG1OdmJUQWVGdzB5TlRBME1qQXhNekF5TXpWYUZ3MHlOVEExTWpBeE16QXlNelZhTUlHZApNUXN3Q1FZRFZRUUdFd0pEVGpFU01CQUdBMVVFQ0F3SlIzVmhibWRrYjI1bk1ROHdEUVlEVlFRSERBWkRZVzUwCmIyNHhGVEFUQmdOVkJBb01ERWR5WldkUVpYSnNhVzVNYVRFU01CQUdBMVVFQ3d3SlEyVnlkRlpoZFd4ME1SVXcKRXdZRFZRUUREQXhqZGk1bmNHd3VZV011WTI0eEp6QWxCZ2txaGtpRzl3MEJDUUVXR0dkeVpXZFFaWEpzYVc1TQphVUJ2ZFhSc2IyOXJMbU52YlRCMk1CQUdCeXFHU000OUFnRUdCU3VCQkFBaUEySUFCTk84N2l2SW9XSHNuUnRzCnNKT09uTDhoWjFmYTRjbjdDTEtlRGdBNlN0eW5aOUw3WHM0Y2RlOW5lKy9WYXRyOXlHL2M4Z010RmN3NkFHb2kKdFZ2UmV4cjhZWmdQUUVHMVFYSjVhVGxCYXFqeVFkQ2N3SmlkWXBKbE1IeWVIc0RuTzZPQmdEQitNRTBHQTFVZApFUVJHTUVTQ0RHTjJMbWR3YkM1aFl5NWpib2NFQ2hJQUFZRVlaM0psWjFCbGNteHBia3hwUUc5MWRHeHZiMnN1ClkyOXRoaFJvZEhSd2N6b3ZMMk4yTG1kd2JDNWhZeTVqYmpBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGwKQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQW9HQ0NxR1NNNDlCQU1DQTRHTEFEQ0Jod0pDQU4zeApwWVRKWXZhc3FHT0tYbXRybVV3Y2lXYUFNYlVFQ09NSTg5ZUl2WVAwVWYzdXM3SjlER2t0NnlhMTkzRWxRUStrClpIMVFFcFBLM3ZHeWxiL094R2ZzQWtGVzZQdUVaS3JsZ2hLU09qdCtuZjJjUjF4ajY5Yy9yTGRxcGNaR00vcisKcHczZ1RZOEl4SUExa0ZTUjFHRjQxQW5oc3lxM1dPeDFFTGpYenJhME5IVkJoZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K")
                .setOldPrivkey("LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1GRUNBUUV3QlFZREsyVndCQ0lFSUljYkxEWEpHa1p3eDJSVWVKMmlNbnhSK05SSHZRc2pFN05MWS8rbWpVYVIKZ1NFQWdGbE9YN3ZBNVYrR3I2RGdoSFVORDNaVHpwQVJ4ZENNdmpqYWZjUFB1TlU9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K")
                .setOldCert("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNmVENDQWkrZ0F3SUJBZ0lSQUorWHIzVVh4eWxGSXA1VXUvbUFTOTh3QlFZREsyVndNSUdlTVFzd0NRWUQKVlFRR0V3SkRUakVTTUJBR0ExVUVDQXdKUjNWaGJtZGtiMjVuTVE4d0RRWURWUVFIREFaRFlXNTBiMjR4RFRBTApCZ05WQkFvTUJGUmxjM1F4RnpBVkJnTlZCQXNNRGtObGNuUldZWFZzZENCVVpYTjBNUmt3RndZRFZRUUREQkJEClpYSjBWbUYxYkhRZ1NXNTBJRU5CTVNjd0pRWUpLb1pJaHZjTkFRa0JGaGhuY21WblVHVnliR2x1VEdsQWIzVjAKYkc5dmF5NWpiMjB3SGhjTk1qVXdOREl3TVRNeE1USXhXaGNOTWpVd05USXdNVE14TVRJeFdqQ0JuVEVMTUFrRwpBMVVFQmhNQ1EwNHhFakFRQmdOVkJBZ01DVWQxWVc1blpHOXVaekVQTUEwR0ExVUVCd3dHUTJGdWRHOXVNUlV3CkV3WURWUVFLREF4SGNtVm5VR1Z5YkdsdVRHa3hFakFRQmdOVkJBc01DVU5sY25SV1lYVnNkREVWTUJNR0ExVUUKQXd3TVkzWXVaM0JzTG1GakxtTnVNU2N3SlFZSktvWklodmNOQVFrQkZoaG5jbVZuVUdWeWJHbHVUR2xBYjNWMApiRzl2YXk1amIyMHdLakFGQmdNclpYQURJUUNBV1U1ZnU4RGxYNGF2b09DRWRRMFBkbFBPa0JIRjBJeStPTnA5Cnc4KzQxYU9CZ0RCK01FMEdBMVVkRVFSR01FU0NER04yTG1kd2JDNWhZeTVqYm9jRUNoSUFBWUVZWjNKbFoxQmwKY214cGJreHBRRzkxZEd4dmIyc3VZMjl0aGhSb2RIUndjem92TDJOMkxtZHdiQzVoWXk1amJqQU9CZ05WSFE4QgpBZjhFQkFNQ0JhQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUFVR0F5dGxjQU5CCkFQMFVxVUliUzZ3LzJiR0JFUkxydVRsQjhWcGx6UWxJa0U4QkNrcFhSQ2FHYWNqMVlIazg4TURLV0FZTnZITmMKMk1RbHZxbUQ0MXlkL05jckZHci9DZ3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K")
                .setNewExpiry(90)
                .setComment("Renewed SSL Certificate.");

        GenResponse response = SslCertGenerator.renewSslCertificate(request);

        log.debug(response.toString());
        log.info("New SSL Private Key: \n {}", new String(java.util.Base64.getDecoder().decode(response.getPrivkey())));
        log.info("New SSL Certificate: \n {}", new String(java.util.Base64.getDecoder().decode(response.getCert())));
        log.info("New SSL Certificate Start Date: {}", response.getNotBefore());
        log.info("New SSL Certificate End Date: {}", response.getNotAfter());
    }

}
