package com.gregperlinli.certvault.certificate;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.gregperlinli.certvault.domain.entities.CertificateDetails;
import jakarta.annotation.Resource;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Test Certificate Decoder
 *
 * @author gregPerlinLi
 * @version 1.0.0
 * @className {@code TestCertDecoder}
 * @date 2025/3/15 16:33
 */
@SpringBootTest
@Slf4j
public class TestCertDecoder {

    @Resource
    private ObjectMapper objectMapper;

    @Test
    public void testDecodeCertificate() throws Exception {
        String certBase64 = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVSVENDQXkyZ0F3SUJBZ0lSQU10MFRDOTFjUGhvdzNFeUM0WlBna1V3RFFZSktvWklodmNOQVFFTEJRQXcKZ1pveEN6QUpCZ05WQkFZVEFrTk9NUkl3RUFZRFZRUUlEQWxIZFdGdVoyUnZibWN4RHpBTkJnTlZCQWNNQmtOaApiblJ2YmpFVk1CTUdBMVVFQ2d3TVIzSmxaMUJsY214cGJreHBNUkl3RUFZRFZRUUxEQWxEWlhKMFZtRjFiSFF4CkVqQVFCZ05WQkFNTUNVTmxjblJXWVhWc2RERW5NQ1VHQ1NxR1NJYjNEUUVKQVJZWVozSmxaMUJsY214cGJreHAKUUc5MWRHeHZiMnN1WTI5dE1CNFhEVEkxTURNeE5qQTVORGN6TVZvWERUSTFNRFF4TlRBNU5EY3pNVm93Z1oweApDekFKQmdOVkJBWVRBa05PTVJJd0VBWURWUVFJREFsSGRXRnVaMlJ2Ym1jeER6QU5CZ05WQkFjTUJrTmhiblJ2CmJqRVZNQk1HQTFVRUNnd01SM0psWjFCbGNteHBia3hwTVJJd0VBWURWUVFMREFsRFpYSjBWbUYxYkhReEZUQVQKQmdOVkJBTU1ER04yTG1kd2JDNWhZeTVqYmpFbk1DVUdDU3FHU0liM0RRRUpBUllZWjNKbFoxQmxjbXhwYmt4cApRRzkxZEd4dmIyc3VZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExN0dLCitKbFpnOTdrYkI2Wm56VWZlOHBZQk81cVNjdW8vektHWGU2UkNCeGNwczZHclRzYWdjOUJQQ3BDcGZzMEdpcnoKQWV2eEhxcks0ZG9DMEIzWkhlUG1YVmluWnA3Zis2b05MOTMrMUZGcWtrVCtKY1NKUXBueFI2ZGx1aFBmRnRKYgpORXJuMVFOS2RsWXEra3dwL3RtQldLT3pZTTBFZFRwWWQ4cWl0NmxYcjlmSFdVNUMrcUhJUHhJZHVyT1pCaSt0ClJyQllGNWJSdXNJTTNDN2JWZ1gxTG04RHF2dmJlZWxzZHoxOHNnQWdDRm80MU5pSldXMXRocW8zTWhkTEVmSU4KaGFPaGtmdFlGdXUxMmFqZkFtTUpnZ3VKOEFEQ0NwR1IyMm5seHRJc012S1hwemQvUENNaG04M1cxTVdXUlpyMgpSU0FTMG9ZR0Q1QW5kRWJJS3dJREFRQUJvNEdBTUg0d1RRWURWUjBSQkVZd1JJSU1ZM1l1WjNCc0xtRmpMbU51Cmh3UUtFZ0FCZ1JobmNtVm5VR1Z5YkdsdVRHbEFiM1YwYkc5dmF5NWpiMjJHRkdoMGRIQnpPaTh2WTNZdVozQnMKTG1GakxtTnVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQgpCUVVIQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFISTNtdXkwaTgwQ1U4VXJsTWpoandRdmIvN2NJU2huCjBlcHJBUFh2UVlPZmpSY3RvWlpJSkk3c0kvVm92WFR1MnBFcDluYTFTQVlqOU81ZzlselJ1aG00TmxKRml6dGgKSC85RjFpa3pPalppbE9VbFVJbWZxQTkzV0crSFNLVjNYbU1kOHFRRTVFMVlzRHZWMzVSVlk4ZGNBYnlBZGxCYwpWckswMTI2ektLbkZxUWdEUmZaVjIwQ1VUT3Jpc1c3VmtBZjZ0bURxajFPYlltam0raEwwSXJIOHZCVkZEdTJsClpRTUREYmtKZFNZUG5KTGl5SkVrOWpXaTNzZ2dscHFIemdFZFAvVlRKVEdCTHFJUE0rcFFLYTE3QnZ6QWZPcm4KRURTRzhOL0cvb1QzV3kyNHFBazB5OVFiZEk4N2dzcHV1VkI4Wk9XNmFGMlAwWnlXMTRhOEUrcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=";
        CertificateDetails certificateDetails = CertDecoder.decodeCertificate(certBase64);
        log.debug("certificateDetails: {}", certificateDetails);

        String json = objectMapper.writeValueAsString(certificateDetails);
        log.info("certificateDetails JSON: {}", json);
    }

}
