name: Frontend CI

on:
  push:
    branches:
      - dev
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            frontend
      - name: Move files out
        run: mv frontend/* . && rm -r frontend
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/Jod
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Build frontend
        run: pnpm run build
      - name: Upload artifact (GitHub)
        if: github.server_url == 'https://github.com'
        uses: actions/upload-artifact@v6
        continue-on-error: true
        with:
          name: frontend
          path: dist
      - name: Upload artifact (GHES)
        if: github.server_url != 'https://github.com'
        uses: christopherhx/gitea-upload-artifact@v4
        continue-on-error: true
        with:
          name: frontend
          path: dist
